import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Navbar/ResponsiveNav";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "sonner";
import { AuthProvider } from "@/lib/auth/AuthContext";
import AOSProvider from "@/components/AOSProvider/AOSProvider";
import ScrollToTop from "@/components/ScrollToTop/ScrollToTop";
import ReactQueryProvider from "@/components/ReactQueryProvider/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ReactQueryProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
          >
            <ResponsiveNav />
            <main role="main" className="flex-1">
              <AOSProvider />
              {children}
              <Toaster position="top-left" richColors />
            </main>
            <ScrollToTop />
            <Footer />
          </body>
        </ReactQueryProvider>
      </AuthProvider>
    </html>
  );
}
